version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/chores_list
      - public-data:/chores_list/public
      - tmp-data:/chores_list/tmp
      - log-data:/chores_list/log
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/chores_list/public
      - tmp-data:/chores_list/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: