version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/.env
      - ./environments/db.production.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/chores_list
      - public-data:/chores_list/public
      - tmp-data:/chores_list/tmp
      - log-data:/chores_list/log
    stdin_open: true
    tty: true
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/chores_list/public
      - tmp-data:/chores_list/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data: